### ISSUE TITLE
[refer to client-rust latest error]

### ISSUE THREAD

**Issue by liujp** [tikv/client-cpp#13]
Question is that:
When I want to refer the lasted rust-client, there is an error which looks like the decency error:

in cargo file modify: 
tikv-client = { git = "https://github.com/tikv/client-rust.git", rev = "5714b2f" }

error:
![image](https://user-images.githubusercontent.com/11934146/160320911-aaef6ef6-23b3-47a6-bbbc-65c1ad106169.png)

**Comment by Smityz** [comment]
I upgraded client-rust in https://github.com/tikv/client-cpp/pull/21
