### ISSUE TITLE
Is the C++ Client still in development?

### ISSUE THREAD

**Issue by haneefmubarak** [tikv/client-cpp#14]
Hi @andylokandy & @JaySon-Huang,

Do you perchance know if this C++ Client for TiKV is still under development? If not, do you know what specific work needs to be done to bring this client up to par functionality-wise with the underlying Rust client?

Thanks for all of your excellent work on all of this!

**Comment by andylokandy** [comment]
client-cpp is out-out-date. But, anyway, it's relatively easy to update it by first upgrading to the latest client-rust and fixing the new interface modification. We're welcome for the contribution.

**Comment by Smityz** [comment]
I upgrade client-rust in https://github.com/tikv/client-cpp/pull/21

**Comment by tisonkun** [comment]
Closed as answered.

There is less focus on driving this repo so you can regard it as "no development". But without any issue for using it, why do we change the software? AFAIK there is no regression tests to ensure that it's production ready so use this library at your risk.

If you spotting any issues, reports and contributions are welcome. I think we still have maintainers to spot on this repo.
